// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt2Jn0CIIPGDmmSajGUffDJ-fLlqfHoTo',
    appId: '1:596282448365:web:7aa44a0c53c1b1d337afe4',
    messagingSenderId: '596282448365',
    projectId: 'authapp-9a7b3',
    authDomain: 'authapp-9a7b3.firebaseapp.com',
    storageBucket: 'authapp-9a7b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjwkdNg9aEofeGzE8lEW5wcPU_69Xhmbs',
    appId: '1:596282448365:android:c97b00b6ae426ef537afe4',
    messagingSenderId: '596282448365',
    projectId: 'authapp-9a7b3',
    storageBucket: 'authapp-9a7b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFniUmIVYwmMMRiDNk529UJoj7AjeSTVU',
    appId: '1:596282448365:ios:9937df0b1d903bae37afe4',
    messagingSenderId: '596282448365',
    projectId: 'authapp-9a7b3',
    storageBucket: 'authapp-9a7b3.appspot.com',
    iosClientId: '596282448365-sc8rveu628lnfdbro2ie027esfk5ragd.apps.googleusercontent.com',
    iosBundleId: 'com.example.a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFniUmIVYwmMMRiDNk529UJoj7AjeSTVU',
    appId: '1:596282448365:ios:9937df0b1d903bae37afe4',
    messagingSenderId: '596282448365',
    projectId: 'authapp-9a7b3',
    storageBucket: 'authapp-9a7b3.appspot.com',
    iosClientId: '596282448365-sc8rveu628lnfdbro2ie027esfk5ragd.apps.googleusercontent.com',
    iosBundleId: 'com.example.a',
  );
}
